# Generated by Django 2.2.17 on 2020-11-24 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201124_0758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={},
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 11, 24, 8, 9, 57, 388208), verbose_name='Опубликована'),
        ),
        migrations.AlterModelTable(
            name='blog',
            table=None,
        ),
    ]
