# Generated by Django 2.2.17 on 2020-11-24 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201124_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 11, 24, 8, 13, 56, 736898), verbose_name='Опубликована'),
        ),
    ]
