# Generated by Django 2.2.17 on 2020-11-30 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201128_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 11, 30, 3, 34, 5, 343318), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.TextField(db_index=True, default=datetime.datetime(2020, 11, 30, 3, 34, 5, 344318), verbose_name='Дата'),
        ),
    ]
