# Generated by Django 2.2.17 on 2020-11-30 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201130_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 1, 2, 17, 17, 791298), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.TextField(db_index=True, default=datetime.datetime(2020, 12, 1, 2, 17, 17, 791298), verbose_name='Дата'),
        ),
    ]
