# Generated by Django 2.2.17 on 2020-11-30 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201201_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 1, 2, 23, 25, 713904), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.TextField(db_index=True, default=datetime.datetime(2020, 12, 1, 2, 23, 25, 714929), verbose_name='Дата'),
        ),
    ]
