# Generated by Django 2.2.17 on 2020-12-01 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201201_0223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-posted'], 'verbose_name': 'статья блога', 'verbose_name_plural': 'статья блога'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 1, 18, 10, 23, 549654), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.TextField(db_index=True, default=datetime.datetime(2020, 12, 1, 18, 10, 23, 550654), verbose_name='Дата'),
        ),
        migrations.AlterModelTable(
            name='blog',
            table='Posts',
        ),
    ]
